DROP DATABASE IF EXISTS BUSCA_PEV;
CREATE DATABASE BUSCA_PEV;
USE BUSCA_PEV;

CREATE TABLE PEV_USER(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);