DROP DATABASE IF EXISTS BUSCA_PEV;
CREATE DATABASE BUSCA_PEV;
USE BUSCA_PEV;

CREATE TABLE PEV_USER(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE PEV_ADMIN(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE PEV_MODERATOR(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PHONE VARCHAR(255) NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE PEV(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CEP VARCHAR(255) NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    DISTRICT VARCHAR(255) NULL,
    NUMBER VARCHAR(255) NOT NULL
);

INSERT INTO PEV (CEP, STREET, DISTRICT, NUMBER)
VALUES ('13060-486','rua ângela stecca pelegrini', 'bairro fodase', '137');